val ScalaJSVersion = Option(System.getenv("SCALAJS_VERSION")).filter(_.nonEmpty).getOrElse("1.7.0")

addSbtPlugin("com.47deg"                 % "sbt-microsites"                % "1.3.4")
addSbtPlugin("com.eed3si9n"              % "sbt-unidoc"                    % "0.4.3")
addSbtPlugin("com.github.tkawachi"       % "sbt-doctest"                   % "0.9.9")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"               % "1.0.0")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"                    % "5.6.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"                  % "0.1.20")
addSbtPlugin("org.portable-scala"        % "sbt-scala-native-crossproject" % "1.1.0")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject"      % "1.1.0")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"                   % ScalaJSVersion)
addSbtPlugin("org.scalameta"             % "sbt-mdoc"                      % "2.2.23")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"                 % "1.8.2")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"                       % "0.4.3")
addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"                     % "1.5.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"                  % "0.10.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"                  % "2.4.6")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"                       % "0.4.3")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"                   % "0.6.3")
addSbtPlugin("io.spray"                  % "sbt-revolver"                  % "0.9.1")
addSbtPlugin("com.codecommit"            % "sbt-github-actions"            % "0.14.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scala3-migrate"            % "0.5.1")
addSbtPlugin("com.github.sbt"            % "sbt-pgp"                       % "2.1.2")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"                  % "2.3")
